window.MANTI_SEED_DATA = {
  "manti_order_records": [
    {
      "id": "PO-1001",
      "type": "Purchase Order",
      "date": "2025-12-23",
      "dueDate": "2026-01-26",
      "customer": "",
      "product": "Jewelry Casting & Equipment",
      "weight": 9,
      "qty": 9,
      "unit": "g",
      "amount": 388220,
      "paidAmount": 388220,
      "status": "Completed",
      "vendor": "SUP-1001",
      "category": "Assets",
      "assetType": "Machinery",
      "billNo": "202 & 14",
      "remark": "-",
      "items": [
        {
          "desc": "Burnout 12X12",
          "qty": "1",
          "rate": "48000",
          "gst": "18",
          "total": "56640.00"
        },
        {
          "desc": "Melting SPL",
          "qty": "1",
          "rate": "23000",
          "gst": "18",
          "total": "27140.00"
        },
        {
          "desc": "Buffing single",
          "qty": "1",
          "rate": "38000",
          "gst": "18",
          "total": "44840.00"
        },
        {
          "desc": "Magnet polish 1 KG",
          "qty": "1",
          "rate": "35000",
          "gst": "18",
          "total": "41300.00"
        },
        {
          "desc": "Drom polish",
          "qty": "1",
          "rate": "23000",
          "gst": "18",
          "total": "27140.00"
        },
        {
          "desc": "Ultra wash 9Ltr",
          "qty": "1",
          "rate": "27000",
          "gst": "18",
          "total": "31860.00"
        },
        {
          "desc": "Water Jet",
          "qty": "1",
          "rate": "28000",
          "gst": "18",
          "total": "33040.00"
        },
        {
          "desc": "Injector",
          "qty": "1",
          "rate": "22000",
          "gst": "18",
          "total": "25960.00"
        },
        {
          "desc": "Casting 500 LPM",
          "qty": "1",
          "rate": "85000",
          "gst": "18",
          "total": "100300.00"
        }
      ]
    },
    {
      "id": "PO-1002",
      "type": "Purchase Order",
      "date": "2026-02-05",
      "dueDate": "2026-02-07",
      "customer": "",
      "product": "3 kg E.W. Scale",
      "weight": 1,
      "qty": 1,
      "unit": "g",
      "amount": 16520,
      "paidAmount": 16520,
      "status": "Completed",
      "vendor": "SUP-1003",
      "category": "Assets",
      "assetType": "Electronics",
      "billNo": "2046/25-26",
      "remark": "Machine No : 260411\nAccuracy : 10 MG",
      "items": [
        {
          "desc": "3 kg E.W.Scale ",
          "qty": "1",
          "rate": "14000",
          "gst": "18",
          "total": "16520.00"
        }
      ]
    }
  ],
  "manti_supplier_kyc_records": [
    {
      "id": "SUP-1001",
      "name": "SAI ENGINEERING",
      "mobile": "9994493941",
      "email": null,
      "address": "5/23 PERUMAL KONAR STREET EDAYARPALAYAM KUNIYAMUTHUR COIMBATORE",
      "gst": "33AJEPA1372Q1Z9",
      "pan": "AJEPA1372Q"
    },
    {
      "id": "SUP-1002",
      "name": "AUGMENT 3DI",
      "mobile": "+91 78068 08545",
      "email": null,
      "address": "No.52,illango Nagar,Avarampalyam Ganapathy-641006 Coimbatore Tamil Nadu",
      "gst": "33ABNFA1691H1ZF",
      "pan": "ABNFA1691H"
    },
    {
      "id": "SUP-1003",
      "name": "VASAVI SCALES",
      "mobile": "9380354043",
      "email": null,
      "address": "No. 105/71, NAINIAPPA NAICKEN STREET, CHENNAI - 600 003",
      "gst": "33AACFV4705B1ZQ",
      "pan": "AACFV4705B"
    },
    {
      "id": "SUP-1004",
      "name": "RKB Designer",
      "mobile": "7550301868",
      "email": "rakeefrkf@gmail.com",
      "address": "nill",
      "gst": "nill",
      "pan": "nill"
    },
    {
      "id": "SUP-1005",
      "name": "Kalai rubber stamps and printings",
      "mobile": "9787574989",
      "email": "Kalairubberstamps@gmail.com",
      "address": "Sf no.99/5,periyanaickenpalayam,coimbatore",
      "gst": "33AXHPA9978PIZO",
      "pan": "AXHPA9978P"
    }
  ],
  "manti_assets": [
    {
      "id": "AST-832197",
      "date": "2025-12-11",
      "name": "Mac M2",
      "notes": "laptop with charger and bag",
      "value": "50000",
      "status": "Active",
      "category": "Electronics",
      "depreciation": "5"
    },
    {
      "id": "AST-1820180",
      "date": "2026-02-05",
      "name": "3 kg e.w.scale-shri vasavi machine no.260411 accuracy:10mg",
      "notes": "Auto-added from PO: PO-1002",
      "value": "16520",
      "status": "Active",
      "category": "Electronics",
      "depreciation": "8"
    },
    {
      "id": "AST-0006490",
      "date": "2026-03-13",
      "name": "Anycubic photon mono m7 pro 3Dprinter",
      "notes": "Auto-added from PO: PO-1001",
      "value": "58004.08",
      "status": "Active",
      "category": "Machinery"
    }
  ],
  "manti_expenses": [
    {
      "id": "EXP-11770762",
      "date": "2026-03-02",
      "account": "Rent Expense",
      "amount": 6080,
      "paidThrough": "Bank Account",
      "vendor": "vijay",
      "reference": "",
      "notes": "include of gst 18%",
      "status": "Payment Pending",
      "total": 6080
    },
    {
      "id": "EXP-11703464",
      "date": "2026-02-03",
      "account": "Rent Expense",
      "amount": 6080,
      "paidThrough": "Bank Account",
      "vendor": "vijay",
      "reference": "",
      "notes": "With GST 18%",
      "status": "Payment Pending",
      "total": 6080
    }
  ],
  "manti_designs": [
    {
      "id": "RG001-1.53-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.53,
      "size": 14,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 888.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG002-1.56-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.56,
      "size": 16,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 902.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG003-1.59-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.59,
      "size": 18,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 915.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG004-1.62-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.62,
      "size": 12,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 929.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG005-1.65-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.65,
      "size": 14,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 942.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG006-1.68-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.68,
      "size": 16,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 956.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG007-1.71-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.71,
      "size": 18,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 969.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG008-1.74-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.74,
      "size": 12,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 983.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG009-1.77-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.77,
      "size": 14,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 996.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG010-1.8-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.8,
      "size": 16,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1010.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG011-1.83-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.83,
      "size": 18,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1023.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG012-1.86-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.86,
      "size": 12,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1037.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG013-1.89-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.89,
      "size": 14,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1050.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG014-1.92-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.92,
      "size": 16,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1064.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG015-1.95-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.95,
      "size": 18,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1077.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG016-1.98-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 1.98,
      "size": 12,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1091.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG017-2.01-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.01,
      "size": 14,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1104.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG018-2.04-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.04,
      "size": 16,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1118.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG019-2.07-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.07,
      "size": 18,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1131.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG020-2.1-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.1,
      "size": 12,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1145.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG021-2.13-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.13,
      "size": 14,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1158.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG022-2.16-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.16,
      "size": 16,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1172.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG023-2.19-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.19,
      "size": 18,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1185.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG024-2.22-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.22,
      "size": 12,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1199.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG025-2.25-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.25,
      "size": 14,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1212.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG026-2.28-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.28,
      "size": 16,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1226.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG027-2.31-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.31,
      "size": 18,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1239.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG028-2.34-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.34,
      "size": 12,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1253.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG029-2.37-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.37,
      "size": 14,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1266.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG030-2.4-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.4,
      "size": 16,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1280.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG031-2.43-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.43,
      "size": 18,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1293.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG032-2.46-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.46,
      "size": 12,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1307.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG033-2.49-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.49,
      "size": 14,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1320.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG034-2.52-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.52,
      "size": 16,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1334.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG035-2.55-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.55,
      "size": 18,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1347.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG036-2.58-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.58,
      "size": 12,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1361.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG037-2.61-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.61,
      "size": 14,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1374.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG038-2.64-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.64,
      "size": 16,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1388.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG039-2.67-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.67,
      "size": 18,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1401.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG040-2.7-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.7,
      "size": 12,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1415.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG041-2.73-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.73,
      "size": 14,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1428.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG042-2.76-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.76,
      "size": 16,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1442.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG043-2.79-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.79,
      "size": 18,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1455.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG044-2.82-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.82,
      "size": 12,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1469.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG045-2.85-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.85,
      "size": 14,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1482.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG046-2.88-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.88,
      "size": 16,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1496.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG047-2.91-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.91,
      "size": 18,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1509.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG048-2.94-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.94,
      "size": 12,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1523.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG049-2.97-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 2.97,
      "size": 14,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1536.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG050-3.0-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.0,
      "size": 16,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1550.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG051-3.03-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.03,
      "size": 18,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1563.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG052-3.06-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.06,
      "size": 12,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1577.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG053-3.09-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.09,
      "size": 14,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1590.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG054-3.12-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.12,
      "size": 16,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1604.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG055-3.15-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.15,
      "size": 18,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1617.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG056-3.18-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.18,
      "size": 12,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1631.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG057-3.21-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.21,
      "size": 14,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1644.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG058-3.24-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.24,
      "size": 16,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1658.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG059-3.27-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.27,
      "size": 18,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1671.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG060-3.3-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.3,
      "size": 12,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1685.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG061-3.33-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.33,
      "size": 14,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1698.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG062-3.36-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.36,
      "size": 16,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1712.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG063-3.39-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.39,
      "size": 18,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1725.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG064-3.42-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.42,
      "size": 12,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1739.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG065-3.45-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.45,
      "size": 14,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1752.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG066-3.48-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.48,
      "size": 16,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1766.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG067-3.51-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.51,
      "size": 18,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1779.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG068-3.54-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.54,
      "size": 12,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1793.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG069-3.57-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.57,
      "size": 14,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1806.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG070-3.6-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.6,
      "size": 16,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1820.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG071-3.63-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.63,
      "size": 18,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1833.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG072-3.66-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.66,
      "size": 12,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1847.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG073-3.69-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.69,
      "size": 14,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1860.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG074-3.72-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.72,
      "size": 16,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1874.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG075-3.75-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.75,
      "size": 18,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1887.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG076-3.78-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.78,
      "size": 12,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1901.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG077-3.81-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.81,
      "size": 14,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1914.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG078-3.84-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.84,
      "size": 16,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1928.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG079-3.87-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.87,
      "size": 18,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1941.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG080-3.9-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.9,
      "size": 12,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1955.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG081-3.93-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.93,
      "size": 14,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1968.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG082-3.96-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.96,
      "size": 16,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1982.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG083-3.99-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 3.99,
      "size": 18,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1995.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG084-4.02-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.02,
      "size": 12,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2009.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG085-4.05-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.05,
      "size": 14,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 2022.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG086-4.08-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.08,
      "size": 16,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 2036.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG087-4.11-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.11,
      "size": 18,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 2049.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG088-4.14-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.14,
      "size": 12,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2063.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG089-4.17-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.17,
      "size": 14,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2076.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG090-4.2-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.2,
      "size": 16,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 2090.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG091-4.23-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.23,
      "size": 18,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 2103.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG092-4.26-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.26,
      "size": 12,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 2117.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG093-4.29-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.29,
      "size": 14,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2130.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG094-4.32-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.32,
      "size": 16,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2144.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG095-4.35-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.35,
      "size": 18,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 2157.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG096-4.38-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.38,
      "size": 12,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 2171.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG097-4.41-14",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.41,
      "size": 14,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 2184.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG098-4.44-16",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.44,
      "size": 16,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2198.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG099-4.47-18",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.47,
      "size": 18,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2211.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG100-4.5-12",
      "category": "Ladies ring",
      "subCategory": "Ladies ring",
      "weight": 4.5,
      "size": 12,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 2225.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG001-3.61-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 3.61,
      "size": 20,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1824.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG002-3.73-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 3.73,
      "size": 22,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1878.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG003-3.84-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 3.84,
      "size": 18,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1928.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG004-3.95-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 3.95,
      "size": 20,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1977.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG005-4.06-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.06,
      "size": 22,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 2027.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG006-4.17-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.17,
      "size": 18,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 2076.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG007-4.29-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.29,
      "size": 20,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 2130.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG008-4.4-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.4,
      "size": 22,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2180.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG009-4.51-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.51,
      "size": 18,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2229.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG010-4.62-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.62,
      "size": 20,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 2279.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG011-4.74-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.74,
      "size": 22,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 2333.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG012-4.85-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.85,
      "size": 18,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 2382.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG013-4.96-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 4.96,
      "size": 20,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2432.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG014-5.08-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.08,
      "size": 22,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2486.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG015-5.19-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.19,
      "size": 18,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 2535.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG016-5.3-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.3,
      "size": 20,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 2585.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG017-5.41-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.41,
      "size": 22,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 2634.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG018-5.53-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.53,
      "size": 18,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2688.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG019-5.64-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.64,
      "size": 20,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2738.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG020-5.75-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.75,
      "size": 22,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 2787.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG021-5.86-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.86,
      "size": 18,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 2837.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG022-5.97-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 5.97,
      "size": 20,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 2886.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG023-6.09-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.09,
      "size": 22,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2940.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG024-6.2-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.2,
      "size": 18,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2990.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG025-6.31-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.31,
      "size": 20,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 3039.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG026-6.43-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.43,
      "size": 22,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 3093.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG027-6.54-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.54,
      "size": 18,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 3143.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG028-6.65-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.65,
      "size": 20,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 3192.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG029-6.76-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.76,
      "size": 22,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 3242.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG030-6.88-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.88,
      "size": 18,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 3296.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG031-6.99-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 6.99,
      "size": 20,
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 3345.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG032-7.1-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.1,
      "size": 22,
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 3395.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG033-7.21-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.21,
      "size": 18,
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 3444.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG034-7.32-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.32,
      "size": 20,
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 3494.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG035-7.44-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.44,
      "size": 22,
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 3548.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG036-7.55-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.55,
      "size": 18,
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 3597.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG037-7.66-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.66,
      "size": 20,
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 3647.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG038-7.77-22",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.77,
      "size": 22,
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 3696.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG039-7.89-18",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 7.89,
      "size": 18,
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 3750.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "RG040-8.0-20",
      "category": "Gents ring",
      "subCategory": "Gents ring",
      "weight": 8.0,
      "size": 20,
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 3800.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG001-8.4-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 8.4,
      "size": "2x6",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 3980.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG002-8.8-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 8.8,
      "size": "2x8",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 4160.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG003-9.2-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 9.2,
      "size": "2x4",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 4340.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG004-9.6-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 9.6,
      "size": "2x6",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 4520.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG005-10.0-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 10.0,
      "size": "2x8",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 4700.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG006-10.4-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 10.4,
      "size": "2x4",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 4880.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG007-10.8-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 10.8,
      "size": "2x6",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 5060.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG008-11.2-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 11.2,
      "size": "2x8",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 5240.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG009-11.6-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 11.6,
      "size": "2x4",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 5420.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG010-12.0-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 12.0,
      "size": "2x6",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 5600.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG011-12.4-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 12.4,
      "size": "2x8",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 5780.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG012-12.8-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 12.8,
      "size": "2x4",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 5960.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG013-13.2-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 13.2,
      "size": "2x6",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 6140.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG014-13.6-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 13.6,
      "size": "2x8",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 6320.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG015-14.0-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 14.0,
      "size": "2x4",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 6500.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG016-14.4-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 14.4,
      "size": "2x6",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 6680.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG017-14.8-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 14.8,
      "size": "2x8",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 6860.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG018-15.2-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 15.2,
      "size": "2x4",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 7040.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG019-15.6-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 15.6,
      "size": "2x6",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 7220.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG020-16.0-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 16.0,
      "size": "2x8",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 7400.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG021-16.4-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 16.4,
      "size": "2x4",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 7580.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG022-16.8-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 16.8,
      "size": "2x6",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 7760.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG023-17.2-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 17.2,
      "size": "2x8",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 7940.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG024-17.6-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 17.6,
      "size": "2x4",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 8120.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG025-18.0-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 18.0,
      "size": "2x6",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 8300.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG026-18.4-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 18.4,
      "size": "2x8",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 8480.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG027-18.8-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 18.8,
      "size": "2x4",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 8660.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG028-19.2-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 19.2,
      "size": "2x6",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 8840.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG029-19.6-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 19.6,
      "size": "2x8",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 9020.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG030-20.0-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 20.0,
      "size": "2x4",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 9200.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG031-20.4-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 20.4,
      "size": "2x6",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 9380.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG032-20.8-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 20.8,
      "size": "2x8",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 9560.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG033-21.2-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 21.2,
      "size": "2x4",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 9740.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG034-21.6-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 21.6,
      "size": "2x6",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 9920.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG035-22.0-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 22.0,
      "size": "2x8",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 10100.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG036-22.4-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 22.4,
      "size": "2x4",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 10280.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG037-22.8-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 22.8,
      "size": "2x6",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 10460.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG038-23.2-2x8",
      "category": "Bangle",
      "subCategory": null,
      "weight": 23.2,
      "size": "2x8",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 10640.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG039-23.6-2x4",
      "category": "Bangle",
      "subCategory": null,
      "weight": 23.6,
      "size": "2x4",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 10820.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "BG040-24.0-2x6",
      "category": "Bangle",
      "subCategory": null,
      "weight": 24.0,
      "size": "2x6",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 11000.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER001-2.13",
      "category": "Earring",
      "subCategory": null,
      "weight": 2.13,
      "size": "",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1158.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER002-2.27",
      "category": "Earring",
      "subCategory": null,
      "weight": 2.27,
      "size": "",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1221.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER003-2.4",
      "category": "Earring",
      "subCategory": null,
      "weight": 2.4,
      "size": "",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1280.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER004-2.53",
      "category": "Earring",
      "subCategory": null,
      "weight": 2.53,
      "size": "",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1338.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER005-2.67",
      "category": "Earring",
      "subCategory": null,
      "weight": 2.67,
      "size": "",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 1401.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER006-2.8",
      "category": "Earring",
      "subCategory": null,
      "weight": 2.8,
      "size": "",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 1460.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER007-2.93",
      "category": "Earring",
      "subCategory": null,
      "weight": 2.93,
      "size": "",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 1518.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER008-3.07",
      "category": "Earring",
      "subCategory": null,
      "weight": 3.07,
      "size": "",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1581.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER009-3.2",
      "category": "Earring",
      "subCategory": null,
      "weight": 3.2,
      "size": "",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1640.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER010-3.33",
      "category": "Earring",
      "subCategory": null,
      "weight": 3.33,
      "size": "",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 1698.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER011-3.47",
      "category": "Earring",
      "subCategory": null,
      "weight": 3.47,
      "size": "",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 1761.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER012-3.6",
      "category": "Earring",
      "subCategory": null,
      "weight": 3.6,
      "size": "",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 1820.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER013-3.73",
      "category": "Earring",
      "subCategory": null,
      "weight": 3.73,
      "size": "",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 1878.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER014-3.87",
      "category": "Earring",
      "subCategory": null,
      "weight": 3.87,
      "size": "",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 1941.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER015-4.0",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.0,
      "size": "",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 2000.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER016-4.13",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.13,
      "size": "",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 2058.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER017-4.27",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.27,
      "size": "",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 2121.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER018-4.4",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.4,
      "size": "",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2180.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER019-4.53",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.53,
      "size": "",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2238.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER020-4.67",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.67,
      "size": "",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 2301.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER021-4.8",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.8,
      "size": "",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 2360.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER022-4.93",
      "category": "Earring",
      "subCategory": null,
      "weight": 4.93,
      "size": "",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 2418.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER023-5.07",
      "category": "Earring",
      "subCategory": null,
      "weight": 5.07,
      "size": "",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2481.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER024-5.2",
      "category": "Earring",
      "subCategory": null,
      "weight": 5.2,
      "size": "",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2540.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER025-5.33",
      "category": "Earring",
      "subCategory": null,
      "weight": 5.33,
      "size": "",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 2598.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER026-5.47",
      "category": "Earring",
      "subCategory": null,
      "weight": 5.47,
      "size": "",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 2661.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER027-5.6",
      "category": "Earring",
      "subCategory": null,
      "weight": 5.6,
      "size": "",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 2720.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER028-5.73",
      "category": "Earring",
      "subCategory": null,
      "weight": 5.73,
      "size": "",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 2778.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER029-5.87",
      "category": "Earring",
      "subCategory": null,
      "weight": 5.87,
      "size": "",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2841.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "ER030-6.0",
      "category": "Earring",
      "subCategory": null,
      "weight": 6.0,
      "size": "",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 2900.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK001-11.56",
      "category": "Necklace",
      "subCategory": null,
      "weight": 11.56,
      "size": "",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 5402.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK002-13.12",
      "category": "Necklace",
      "subCategory": null,
      "weight": 13.12,
      "size": "",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 6104.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK003-14.69",
      "category": "Necklace",
      "subCategory": null,
      "weight": 14.69,
      "size": "",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 6810.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK004-16.25",
      "category": "Necklace",
      "subCategory": null,
      "weight": 16.25,
      "size": "",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 7512.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK005-17.81",
      "category": "Necklace",
      "subCategory": null,
      "weight": 17.81,
      "size": "",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 8214.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK006-19.38",
      "category": "Necklace",
      "subCategory": null,
      "weight": 19.38,
      "size": "",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 8921.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK007-20.94",
      "category": "Necklace",
      "subCategory": null,
      "weight": 20.94,
      "size": "",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 9623.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK008-22.5",
      "category": "Necklace",
      "subCategory": null,
      "weight": 22.5,
      "size": "",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 10325.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK009-24.06",
      "category": "Necklace",
      "subCategory": null,
      "weight": 24.06,
      "size": "",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 11027.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK010-25.62",
      "category": "Necklace",
      "subCategory": null,
      "weight": 25.62,
      "size": "",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 11729.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK011-27.19",
      "category": "Necklace",
      "subCategory": null,
      "weight": 27.19,
      "size": "",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 12435.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK012-28.75",
      "category": "Necklace",
      "subCategory": null,
      "weight": 28.75,
      "size": "",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 13137.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK013-30.31",
      "category": "Necklace",
      "subCategory": null,
      "weight": 30.31,
      "size": "",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 13839.5,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK014-31.88",
      "category": "Necklace",
      "subCategory": null,
      "weight": 31.88,
      "size": "",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 14546.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK015-33.44",
      "category": "Necklace",
      "subCategory": null,
      "weight": 33.44,
      "size": "",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 15248.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "NK016-35.0",
      "category": "Necklace",
      "subCategory": null,
      "weight": 35.0,
      "size": "",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 15950.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX001-4.2",
      "category": "Mix",
      "subCategory": null,
      "weight": 4.2,
      "size": "",
      "designType": "Mold",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 2090.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX002-5.4",
      "category": "Mix",
      "subCategory": null,
      "weight": 5.4,
      "size": "",
      "designType": "STL",
      "designerName": "RKB Designer",
      "purchaseValue": 2630.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX003-6.6",
      "category": "Mix",
      "subCategory": null,
      "weight": 6.6,
      "size": "",
      "designType": "Mold",
      "designerName": "Manti In-House",
      "purchaseValue": 3170.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX004-7.8",
      "category": "Mix",
      "subCategory": null,
      "weight": 7.8,
      "size": "",
      "designType": "STL",
      "designerName": "Devi Artisans",
      "purchaseValue": 3710.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX005-9.0",
      "category": "Mix",
      "subCategory": null,
      "weight": 9.0,
      "size": "",
      "designType": "Mold",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 4250.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX006-10.2",
      "category": "Mix",
      "subCategory": null,
      "weight": 10.2,
      "size": "",
      "designType": "STL",
      "designerName": "Rajesh Crafts",
      "purchaseValue": 4790.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX007-11.4",
      "category": "Mix",
      "subCategory": null,
      "weight": 11.4,
      "size": "",
      "designType": "Mold",
      "designerName": "RKB Designer",
      "purchaseValue": 5330.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX008-12.6",
      "category": "Mix",
      "subCategory": null,
      "weight": 12.6,
      "size": "",
      "designType": "STL",
      "designerName": "Manti In-House",
      "purchaseValue": 5870.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX009-13.8",
      "category": "Mix",
      "subCategory": null,
      "weight": 13.8,
      "size": "",
      "designType": "Mold",
      "designerName": "Devi Artisans",
      "purchaseValue": 6410.0,
      "imageUrl": "",
      "_sourcePO": ""
    },
    {
      "id": "MX010-15.0",
      "category": "Mix",
      "subCategory": null,
      "weight": 15.0,
      "size": "",
      "designType": "STL",
      "designerName": "AUGMENT 3DI",
      "purchaseValue": 6950.0,
      "imageUrl": "",
      "_sourcePO": ""
    }
  ]
};
